### Update an existing patient entity
PUT http://localhost:4000/patients/22ebf148-721e-43b8-96d5-7c0ba037f740
Content-Type: application/json

{
  "name": "John Doe20",
  "email": "test2@example.com",
  "address": "123 main street",
  "dateOfBirth": "1999-12-21",
  "registeredDate": "2025-01-23"
}
###